package dev.shardingbase.protocol;

/** Message families understood by the prototype transport. */
public enum MessageType {
    AUTHENTICATE_NODE_REQUEST,
    AUTHENTICATE_NODE_RESPONSE,
    VALIDATE_BACKEND_REQUEST,
    VALIDATE_BACKEND_RESPONSE,
    HEARTBEAT,
    HEARTBEAT_ACK,
    PLAYER_SNAPSHOT_PREPARE,
    PLAYER_SNAPSHOT_CAPTURE,
    PLAYER_SNAPSHOT_STAGE,
    PLAYER_SNAPSHOT_FETCH,
    PLAYER_SNAPSHOT_FETCH_RESPONSE,
    PLAYER_SNAPSHOT_ACK,
    PLAYER_SETTINGS_GET,
    PLAYER_SETTINGS_SET,
    PLAYER_SETTINGS_RESPONSE,
    BACKEND_POLL,
    BACKEND_POLL_EMPTY,
    ERROR,
    FILE_BEGIN,
    FILE_CHUNK,
    FILE_ACK,
    FILE_COMPLETE,
    FILE_ABORT
}
